apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-downloader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: youtube-downloader-pv
  storageClassName: ""
