- name: Deploy YouTube Downloader Application on Ubuntu 24.04
  hosts: all
  become: yes
  tasks:
      - name: Check if KIND is installed
      shell: test -x /usr/local/bin/kind
      register: kind_installed
      ignore_errors: yes

    - name: Ensure KIND is installed
      fail:
        msg: "KIND is not installed! Please install it or add it to the PATH."
      when: kind_installed.rc != 0

    - name: Check if Kubernetes cluster exists
      shell: /usr/local/bin/kind get clusters | grep -w youtube-cluster
      register: cluster_exists
      ignore_errors: yes

    - name: Create Kubernetes cluster (if not exists)
      command: /usr/local/bin/kind create cluster --name youtube-cluster
      when: cluster_exists.rc != 0



    - name: Apply Kubernetes Manifests
      shell: /usr/local/bin/kubectl apply -f deployment.yaml -f service.yaml 
